### ISSUE TITLE
Human Sacrifices Problem

### ISSUE THREAD

**Issue by Kirito1** [Gstayton/GeometricMagic#2]
On my server whenever I try to do human transmutation it just says the usual "you have committed the taboo, crafting is your sacrifice, knowledge is your power" Its not letting me /setcircle commands still. What do i do? Is this a bug or no? Please help soon

**Comment by Gstayton** [comment]
Currently, even if it was a bug, craftbukkit jars are not longer obtainable, so I won't be able to fix this.
/setcircle is something I didn't get around to future-proofing against the Minecraft updates, so it's possible a recent update changed something it made use of.
Given the situation, I'm sorry to say, but it seems that any and all current bugs will have to wait until the Sponge project is finished, and I can simple re-write the plugin for that.
